# Generated by Django 2.0.3 on 2018-04-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=250)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(upload_to='')),
                ('tanggal_terbit', models.DateTimeField(verbose_name='tanggal terbit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.ProfilPengguna')),
            ],
            options={
                'ordering': ('created_at', 'updated_at'),
            },
        ),
    ]
