# Generated by Django 2.0.3 on 2018-04-13 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='sinopsis',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
