# Generated by Django 2.0.3 on 2018-04-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180416_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
