# Generated by Django 2.0.3 on 2018-04-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='sinopsis',
            new_name='deskripsi_singkat',
        ),
    ]
