# Generated by Django 2.0.3 on 2018-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devisi',
            options={'ordering': ('created_at', 'updated_at'), 'verbose_name_plural': 'Devisi'},
        ),
        migrations.AlterField(
            model_name='devisi',
            name='nama',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
