# Generated by Django 2.0.3 on 2018-04-05 22:52

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilorganisasi',
            name='favicon',
            field=models.ImageField(default=datetime.datetime(2018, 4, 5, 22, 51, 47, 627949, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilorganisasi',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
