# Generated by Django 2.0.3 on 2018-04-13 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20180406_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilorganisasi',
            name='misi',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilorganisasi',
            name='profil_singkat',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilorganisasi',
            name='visi',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilorganisasi',
            name='website',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
