# Generated by Django 2.0.3 on 2018-04-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_klien'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeri',
            options={'ordering': ('created_at', 'updated_at'), 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='klien',
            options={'ordering': ('created_at', 'updated_at'), 'verbose_name_plural': 'Klien'},
        ),
        migrations.AlterModelOptions(
            name='profilorganisasi',
            options={'ordering': ('created_at', 'updated_at'), 'verbose_name_plural': 'Profil Organisasi'},
        ),
        migrations.AlterModelOptions(
            name='sosialmedia',
            options={'ordering': ('created_at', 'updated_at'), 'verbose_name_plural': 'Sosial Media'},
        ),
    ]
