# Generated by Django 2.0.3 on 2018-04-13 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20180414_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilorganisasi',
            name='profil_lengkap',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
