# Generated by Django 2.0.3 on 2018-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_profilorganisasi_profil_lengkap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi_singkat', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at', 'updated_at'),
            },
        ),
    ]
