# Generated by Django 2.0.3 on 2018-04-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_galeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='galeri',
            name='banner',
            field=models.BooleanField(default=False, help_text='Apakah gambar ini akan dijadikan sebagai banner?'),
        ),
    ]
