# Generated by Django 2.0.3 on 2018-04-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20180414_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
